name: flutter_timer
description: Flutter timer
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.21.0
  equatable: ^0.2.0
  wave: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.3.0 <2.0.0"

flutter:
  uses-material-design: true
