name: hn_app
description: The boring show project
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: ^5.1.2
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  http: 0.12.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.7.1
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <3.0.0'
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
